package org.example.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.example.dataobject.ItemDo;
import org.example.dataobject.ItemDoExample;

public interface ItemDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Wed Feb 09 23:46:49 CST 2022
     */
    long countByExample(ItemDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Wed Feb 09 23:46:49 CST 2022
     */
    int deleteByExample(ItemDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Wed Feb 09 23:46:49 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Wed Feb 09 23:46:49 CST 2022
     */
    int insert(ItemDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Wed Feb 09 23:46:49 CST 2022
     */
    int insertSelective(ItemDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Wed Feb 09 23:46:49 CST 2022
     */
    List<ItemDo> selectByExample(ItemDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Wed Feb 09 23:46:49 CST 2022
     */
    ItemDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Wed Feb 09 23:46:49 CST 2022
     */
    int updateByExampleSelective(@Param("record") ItemDo record, @Param("example") ItemDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Wed Feb 09 23:46:49 CST 2022
     */
    int updateByExample(@Param("record") ItemDo record, @Param("example") ItemDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Wed Feb 09 23:46:49 CST 2022
     */
    int updateByPrimaryKeySelective(ItemDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Wed Feb 09 23:46:49 CST 2022
     */
    int updateByPrimaryKey(ItemDo record);

    List<ItemDo> listItem();

    int increaseSales(@Param("id") Integer id, @Param("amount") Integer amount);
}