package org.example.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.example.dataobject.OrderDo;
import org.example.dataobject.OrderDoExample;

public interface OrderDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Sat Feb 12 18:30:52 CST 2022
     */
    long countByExample(OrderDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Sat Feb 12 18:30:52 CST 2022
     */
    int deleteByExample(OrderDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Sat Feb 12 18:30:52 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Sat Feb 12 18:30:52 CST 2022
     */
    int insert(OrderDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Sat Feb 12 18:30:52 CST 2022
     */
    int insertSelective(OrderDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Sat Feb 12 18:30:52 CST 2022
     */
    List<OrderDo> selectByExample(OrderDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Sat Feb 12 18:30:52 CST 2022
     */
    OrderDo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Sat Feb 12 18:30:52 CST 2022
     */
    int updateByExampleSelective(@Param("record") OrderDo record, @Param("example") OrderDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Sat Feb 12 18:30:52 CST 2022
     */
    int updateByExample(@Param("record") OrderDo record, @Param("example") OrderDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Sat Feb 12 18:30:52 CST 2022
     */
    int updateByPrimaryKeySelective(OrderDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Sat Feb 12 18:30:52 CST 2022
     */
    int updateByPrimaryKey(OrderDo record);
}