package org.example.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.example.dataobject.PromoDo;
import org.example.dataobject.PromoDoExample;

public interface PromoDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Sat Feb 12 18:30:52 CST 2022
     */
    long countByExample(PromoDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Sat Feb 12 18:30:52 CST 2022
     */
    int deleteByExample(PromoDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Sat Feb 12 18:30:52 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Sat Feb 12 18:30:52 CST 2022
     */
    int insert(PromoDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Sat Feb 12 18:30:52 CST 2022
     */
    int insertSelective(PromoDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Sat Feb 12 18:30:52 CST 2022
     */
    List<PromoDo> selectByExample(PromoDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Sat Feb 12 18:30:52 CST 2022
     */
    PromoDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Sat Feb 12 18:30:52 CST 2022
     */
    int updateByExampleSelective(@Param("record") PromoDo record, @Param("example") PromoDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Sat Feb 12 18:30:52 CST 2022
     */
    int updateByExample(@Param("record") PromoDo record, @Param("example") PromoDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Sat Feb 12 18:30:52 CST 2022
     */
    int updateByPrimaryKeySelective(PromoDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Sat Feb 12 18:30:52 CST 2022
     */
    int updateByPrimaryKey(PromoDo record);

    PromoDo selectByItemId(Integer itemId);
}