package org.example.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.example.dataobject.SequenceDo;
import org.example.dataobject.SequenceDoExample;

public interface SequenceDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sat Feb 12 18:30:52 CST 2022
     */
    long countByExample(SequenceDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sat Feb 12 18:30:52 CST 2022
     */
    int deleteByExample(SequenceDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sat Feb 12 18:30:52 CST 2022
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sat Feb 12 18:30:52 CST 2022
     */
    int insert(SequenceDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sat Feb 12 18:30:52 CST 2022
     */
    int insertSelective(SequenceDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sat Feb 12 18:30:52 CST 2022
     */
    List<SequenceDo> selectByExample(SequenceDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sat Feb 12 18:30:52 CST 2022
     */
    SequenceDo selectByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sat Feb 12 18:30:52 CST 2022
     */
    int updateByExampleSelective(@Param("record") SequenceDo record, @Param("example") SequenceDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sat Feb 12 18:30:52 CST 2022
     */
    int updateByExample(@Param("record") SequenceDo record, @Param("example") SequenceDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sat Feb 12 18:30:52 CST 2022
     */
    int updateByPrimaryKeySelective(SequenceDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sat Feb 12 18:30:52 CST 2022
     */
    int updateByPrimaryKey(SequenceDo record);

    SequenceDo getSequenceByName(String name);
}